version: '3.6'

services:

  redis:
    container_name: redis
    image: redis:latest
    tty: true
    restart: always
    network_mode: host
    ports:
      - 6379:6379
    volumes:
      - ./data/redis/tmp:/var/_data/

  mysql:
    container_name: mysql
    image: mysql:latest
    tty: true
    restart: always
    network_mode: host
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql/tmp:/var/_data
    environment:
      - MYSQL_ROOT_PASSWORD=123