version: '3.6'

services:

  laravel_web:
    container_name: laravel_web
    image: php:8.1.1-apache
    tty: true
    restart: always
    network_mode: host
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - ./web:/var/www/html
      - ./data/laravel:/var/_data

  laravel_db:
    container_name: laravel_db
    image: mariadb:latest
    tty: true
    restart: always
    network_mode: host
    ports:
      - 3306:3306
    volumes:
      - ./data/mariadb:/var/_data
    environment:
      - MARIADB_ROOT_PASSWORD=123

  redis:
    container_name: redis
    image: redis:latest
    tty: true
    restart: always
    network_mode: host
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/var/_data