version: '3.6'

services:

  php:
    container_name: php
    image: php:8.0-apache
    tty: true
    restart: always
    network_mode: host
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - ./data/php:/var/_data

  rust:
    container_name: rust
    image: rust:latest
    tty: true
    restart: always
    network_mode: host
    ports:
      - 8000:8000
    volumes:
      - ./data/rust:/var/_data

  redis:
    container_name: redis
    image: redis:latest
    tty: true
    restart: always
    network_mode: host
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/var/_data

  mysql:
    container_name: mysql
    image: mysql:latest
    tty: true
    restart: always
    network_mode: host
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/_data
    environment:
      - MYSQL_ROOT_PASSWORD=123
